menu:
    - title: Installing Anaconda Server
      url : 'index.html'
    - title: Advanced Install options
      url : 'advanced.html'
    - title: Trouble Shoot Your Anaconda Server installation
      url : 'troubleshoot.html'
    - title: Server Maintenance
      url : 'maintenance.html'
    - title: Client Configuration
      url : 'configuration.html'
    - title: Mirroring PyPI
      url : 'pypi-mirror.html'
